### ISSUE TITLE
Adding check for Criterion 0.1 < Iyc/Iy < 0.9  in 10-27-2-1

### ISSUE THREAD

**Issue by AliranjbarCivil** [ebrahimraeyat/OSAFE#10]
با درود بر جناب آقای مهندس
وقت شما بخیر
لطفا در صورت امکان در آپدیت های بعدی نرم افزار قابلیت کنترل رابطه موجود در بند 10-2-7-2-1 از مبحث دهم مقررات ملی ساختمان مربوط به شرط طراحی اعضای تحت اثر توام لنگر خمشی و نیروی محوری رو برای مقاطع معادل در نرم افزار اعمال نمایید.
با تشکر
![photo_2018-11-16_09-23-46](https://user-images.githubusercontent.com/44951744/48600515-62a78980-e981-11e8-9b3b-19781180bb22.jpg)

**Comment by ebrahimraeyat** [comment]
سلام. فقط یه نکته که باید روشن بشه:
مقاطع دوبل با ورق آیا ورق + بال مقطع یا مقاطع اصلی با هم حساب میشن؟
و اینکه اگر با هم حساب میشن یعنی باید حول مرکز سطح بال و ورق ممان اینرسی رو حساب کنیم؟
یک مثال اگر دارید برای این مورد عکسش رو قرار بدید.

**Comment by ebrahimraeyat** [comment]
![image](https://user-images.githubusercontent.com/8196112/48580283-ac0ebf00-e916-11e8-8682-d95d17129e12.png)

**Comment by ebrahimraeyat** [comment]
It is not needed anymore.
