### ISSUE TITLE
create report for load assing in etabs

### ISSUE THREAD

**Issue by ebrahimraeyat** [ebrahimraeyat/OSAFE#17]
create a report in word format that show loads in frames.

**Comment by salmanishere** [comment]
It would be nice if also add the report not only in *docx* format but also [odt](https://en.wikipedia.org/wiki/OpenDocument) format, for those who want to stay away from MS Office.

**Comment by ebrahimraeyat** [comment]
I use python docx library for exporting to _docx_ , but both of microsoft word and open office can open docx and odt format. all of my users don't know about odt!

**Comment by ebrahimraeyat** [comment]
I think CSI ETABS  has many bugs and since the etabs is closed source software, it's not valuable to dedicate more time for it. I want to invest my time on a bigger project, XCFEM that belongs to community and valuable to work on it. thanks @salmanishere  i will use your experience in this field.

**Comment by ebrahimraeyat** [comment]
not related to this software any more.
