### ISSUE TITLE
در خواست راهنمایی

### ISSUE THREAD

**Issue by hasanzade68** [ebrahimraeyat/OSAFE#19]
با تشکر از زحمات شما
بنده به تازگی با کارهای شما آشنا شدم.
سوالی داشتم و اون اینکه آیانیاز قطعی به نصب freecad داریم یا نه؟و اینکه f1 رو هم میزنم هلپ کار نمیکنه.

**Comment by salmanishere** [comment]
yes, you need FreeCAD.

**Comment by hasanzade68** [comment]
Tanks for answering.
But civiltools work whiteout FreeCad.
Why is necessary to install it?

**Comment by salmanishere** [comment]
for example, it has been used for drawing the objects.

**Comment by ebrahimraeyat** [comment]
Hi, civiltools don't require FreeCAD, but this is Civil! than till now have punch WorkBench in FreeCAD. you must follow this link for installation:
http://ebrahimraeyat.blog.ir/post/install_github

I will try to provide stand alone installer for punch application.

**Comment by salmanishere** [comment]
> tanks a lot. i request that develop civiltools So that it can working in all field without any other software requestment.
> thank YOU.

Thank would be a really fascinating thing to do so. Would you also help if we commence such a project?

**Comment by ebrahimraeyat** [comment]
what is bad about FreeCAD or any other software that civiltools may be required them? we can use result of other work in open source world!

**Comment by luzpaz** [comment]
Anything left to address in this ticket?

**Comment by ebrahimraeyat** [comment]
Thanks @luzpaz . Now civilTools and OSAFE integrated into FreeCAD. If you want to install civilTools stand alone, you must download last version, but I don't update this stand alone package, instead updating civilTools in FreeCAD.

https://github.com/ebrahimraeyat/civilTools/releases/tag/v6

https://github.com/ebrahimraeyat/civilTools
