### ISSUE TITLE
Add package.xml metadata

### ISSUE THREAD

**Issue by luzpaz** [ebrahimraeyat/OSAFE#33]
https://github.com/FreeCAD/FreeCAD-addons/issues/200

**Comment by ebrahimraeyat** [comment]
done with https://github.com/ebrahimraeyat/OSAFE/commit/f3bccd1c8475e59d24fd5fa1db9ed7074996e97e

**Comment by ebrahimraeyat** [comment]
I will close it, it seems it has no issue.
