### ISSUE TITLE
Hardcoded custom path

### ISSUE THREAD

**Issue by luzpaz** [ebrahimraeyat/OSAFE#36]
https://github.com/ebrahimraeyat/OSAFE/blob/8ac7dab8b1cf530dcf3264809dac4a9627ed9d3e/safe/punch/safe_read_write_f2k.py#L8

**Comment by ebrahimraeyat** [comment]
Thanks. Fixed with 68b794c6e6a58e6d0e34000cea4a40e78f2a1d64

**Comment by luzpaz** [comment]
Fix is incomplete. Hardcoded path still remains

**Comment by luzpaz** [comment]
Fixed in latest master
